import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-[1200px] mx-auto px-4 mt-[3rem]">
          <header className="mb-[2rem]">
            <h1>BilgiApp v1.0</h1>
            <nav className="py-[1rem]">
              <Link href="/">Ana Sayfa</Link>
              <Link href="/uyeler">Üyeler</Link>
            </nav>
          </header>

          <main className="mb-[2rem]">{children}</main>

          <footer>
            <p>&copy; 2025 BilgiApp</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
